baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hugo Bookshop Starter"
_enabled_editors = ["visual", "content"]

[module]
replacements = "local/component-library -> ../component-library"

[[module.imports]]
path = 'local/component-library'

[[module.imports]]
path = 'github.com/cloudcannon/bookshop/hugo/v3'
